---
title: "Hans-Hackathon"
author: Sebastian Sauer
date: today
toc: true
---

# Willkommen zum Projekt "Hans-Hackathon"!



Come to the HaNS-Side: we have [videos](https://www.youtube.com/watch?v=HAjXzW2v7OA).

## Gegenstand und Ziel

In diesem Modul analysieren Sie die Klickdaten zum KI-Tool [HaNS](https://www.th-nuernberg.de/einrichtungen-gesamt/in-institute/zentrum-fuer-kuenstliche-intelligenz-kiz/projekte/hans/).

Ziel ist es, das Tool HaNS zu evaluieren. Die Klickdaten sollen genutzt werden, um den Nutzen des Tools für die Studierenden besser einschätzen zu können. Darüber hinaus soll verstanden werden, wie Studierende das Tool zum Lernen nutzen, und wie das Tool verbessert werden kann, um das Lernen noch erfolgreicher zu gestalten.


## Kursaufbau und Didaktik 

Der grundlegende Aufbau ist, dass den Studierenden jede Woche eine "Challenge" ("Herausforderung", im Sinne eines Aufgabenpakets) präsentiert wird, die bis zur nächsten Woche gelöst werden soll.

Im Unterricht wird Material, das zur Lösung der Aufgabe nötig ist, besprochen oder es wird auf das Material verwiesen. 
In der folgenden Stunde stellt die Lehrkraft dann eine Musterlösung vor und bespricht die von den Studierenden eingereichte Lösung.
Dann wird wiederum eine neue Challenge angegangen usw.



## Tipps


- Chatbots wie ChatGPT können Ihnen helfen, Ihre Idee in Code umzusetzen.